services:
  backend:
    build: ./DevEstate.Api
    container_name: devestate-backend
    ports:
      - "5086:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ./DevEstate.Api/Uploads:/app/Uploads
    restart: unless-stopped

  frontend:
    build: ./DevEstate.Web
    container_name: devestate-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
